version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      SA_PASSWORD: SqlServerDocker@
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      MSSQL_DATABASE: CleanArchMvc
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
